### ISSUE TITLE
Scraping is broken

### ISSUE THREAD

**Issue by darkenvy** [plexinc-plugins/TED-Talks.bundle#18]
All the options on the channel are broken except the immediate results from "newest releases", "most viewed" and "Trending Now". All the other options with sub-genres do not work and result in "Sorry, we couldn't load the requested content". I am guessing that the API or the pages that the data is scraped from changed as TED changed their site.

**Comment by sander1** [comment]
First batch of fixes in https://github.com/plexinc-plugins/TED-Talks.bundle/commit/e1d9d91569d038543f26f9c5baadf3b10cbf1f22

**Comment by darkenvy** [comment]
Fast fix. Thanks for that :D.
